name: Build & Publish Release

on: [workflow_dispatch]

jobs:
  BuildAndPublish:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - name: Build DigitalRiseModel.MonoGame
      run: dotnet build DigitalRiseModel.MonoGame.sln --configuration Release
    - name: Test
      run: dotnet test DigitalRiseModel.MonoGame.sln
    - name: Install NuGet
      uses: NuGet/setup-nuget@v2
    - name: Publish DigitalRiseModel.MonoGame to NuGet
      run: nuget.exe push Source\DigitalRiseModel\bin\Release\DigitalRiseModel.MonoGame.*.nupkg ${{secrets.NUGET_APIKEY}} -Source https://api.nuget.org/v3/index.json
